<?php

/*
Diese Datei ist eine Ergänzung zum Skript collectPersons.php.
Die Liste ermöglicht es, Namen für einzelne Personen oder Körperschaften vorzugeben.
Für jede einzelne wird ein assoziatives Array in das Array $amendments eingefügt. Als Index 
steht die GND-Nummer. Als Wert steht wiederum ein assoziatives Array, in dem für ein oder 
mehrere Felder Werte nach dem Schema 'Feldname' => 'Feldinhalt' neu vergeben werden können.
Feldname kann sein: vorname, nachname, name, beiname, titel, zaehlung, koerperschaftsname, sortiername.

Das Umlenken von Sortiernamen ist außerdem auf Ebene der person möglich, s. dazu person->replaceSortingName()
Diese Funktion bewirkt, dass dublette Einträge überhaupt nicht als eigene person in die personList gelangen.
*/

$amendmentsGND = array(
	'1042346275' => array('sortiername' => ''), //Helwing, Akademische Verlagsbuchhandlung
	'118683969' => array('sortiername' => 'Fleury, André Hercule Cardinal de'),
	'120530791' => array('sortiername' => 'Croÿ, Charles III. de'),
	'118557203' => array('sortiername' => 'Jean de Meung'),
	'118577700' => array('sortiername' => 'Margarete, Frankreich, Königin'),
	'118637649' => array('sortiername' => 'Albertus Magnus'),
	'100942040' => array('sortiername' => 'Del Garbo, Tommaso'),
	'104066822' => array('sortiername' => 'Guglielmo, Mantua, Herzog'),
	'118768522' => array('sortiername' => 'Vincenzo I., Mantua, Herzog'),
	'12959203X' => array('sortiername' => 'Christoph, Brixen, Bischof'),
	'119543052' => array('sortiername' => 'Manderscheidt-Blanckenheim, Jean de'),
	'11859169X' => array('sortiername' => 'Paracelsus'),
	'104081589' => array('sortiername' => 'Portaleone, Avraham ben Da&#x1E7F;id'),
	'129746436' => array('sortiername' => 'Tenison, Thomas'),
	'118507036' => array('sortiername' => 'Basilius, Valentinus'),
	'121292215' => array('sortiername' => 'Zur Lippe- Brake, Amalie'),
	'1008744-8' => array('sortiername' => ''), //Cambridge University Press
	'10211112X' => array('sortiername' => 'Ludwig VI. von der Pfalz'),
	'119184923' => array('sortiername' => 'Flamel, Nicolas'),
	'118738712' => array('sortiername' => 'Ottheinrich Kurfürst von der Pfalz'),
	'11978291X' => array('sortiername' => 'P. Dr.'),
	'6146279-2' => array('sortiername' => 'Löhneysen, Georg Engelhard von, Privatpresse'),
	'119204150' => array('sortiername' => 'Richard Pfalzgraf zu Pfalz-Simmern'),
	'' => array('sortiername' => ''),
	'' => array('sortiername' => ''),
	'' => array('sortiername' => ''),
	'' => array('sortiername' => ''),
	'' => array('sortiername' => ''),
	'1037525493' => array('sortiername' => 'Bellère, Balthazar', 'nachname' => 'Bellère')
);

$amendmentsSortingName = array(
	'Dillenius, Justus Fridericus' => 'Dillenius, Justus Friedrich',
	'Adolphus-Fridericus Dux Megapolitano' => 'Adolf Friedrich I., Mecklenburg, Herzog',
	'Adolphus-Fridericus Dux Megapolitanus' => 'Adolf Friedrich I., Mecklenburg, Herzog',
	'Adolphus-Fridericus Megapolitano, Dux' => 'Adolf Friedrich I., Mecklenburg, Herzog',
	'Anomaeus, Joh. Joachimus' => 'Anomoeus, Johannes Joachim',
	'Antonius Gunterus Comes in Oldenburg' => 'Anton Günther Graf von Oldenburg',
	'Antonius Guntherus Comes in Oldenburg & Delmenhorst' => 'Anton Günther Graf von Oldenburg',
	'Arndt. Joh.' => 'Arndt, Johann',
	'Arnoldus de Villaenova' => 'Arnoldus de Villa Nova',
	'Artephius' => 'Artephius Philosophus',
	'August Wolfenbüttel, Herzog' => 'August Braunschweig-Lüneburg, Herzog, 1579-1666',
	'Augustus Juniorus Dux Brunswicensis & Lünaeburgensis &c.' => 'August Braunschweig-Lüneburg, Herzog, 1579-1666',
	'Augustus Fürst zu Anhalt' => 'August Anhalt-Köthen, Fürst',
	'Augustus Princeps Anhaltinus' => 'August Anhalt-Köthen, Fürst',
	'Bacon, Rogerus' => 'Bacon, Roger',
	'Balbian, Joos' => 'Balbian, Joos a',
	'Beyerus, Johannes Hartmannus' => 'Beyer, Johann Hartmann',
	'Bollingerus, Ulricus' => 'Bollinger, Ulrich',
	'Bomsdorf, Jobus a' => 'Bomsdorf, Jacob von',
	'Brelerus, Melchior' => 'Breler, Melchior',
	'Brendelius, Zacharias' => 'Brendel, Zacharias',
	'Burenneus, Rudolphus' => 'Burennaeus, Rudolph',
	'Burennus, Rudolphus' => 'Burennaeus, Rudolph',
	'Burggravius, Johannes Ernestus' => 'Burggrav, Johann Ernst',
	'Burmeister, Johannes' => 'Burmeister, Johann',
	'Burmeisterus, Johannes' => 'Burmeister, Johann',
	'Buttet' => 'Buttet, Marc-Claude de',
	'Bütnerus, Johannes' => 'Büttner, Johann',
	'Christianus Ascanieae, Comes' => 'Christian I., Anhalt-Bernburg, Fürst',
	'Christianus Comes Ascaniae' => 'Christian I., Anhalt-Bernburg, Fürst',
	'Clauderus, Gabriel' => 'Clauder, Gabriel',
	'Colbertus, Joannes Baptista' => 'Colbert, Jean Baptiste',
	'Conringius, Hermannus' => 'Conring, Hermann',
	'Dietzel, Caspar' => 'Dietzel, Kaspar',
	'Dornau, Caspar' => 'Dornavius a Dornaw, Caspar',
	'Doude, Arnoldus' => 'Doude, Aernout',	
	'Drexel, Joannes' => 'Drexel, Johannes',
	'DuChesne, Joseph' => 'Du Chesne, Joseph',
	'Duval, Robert' => 'Duval, Robert, Vallensis',
	'Ellenberger, Henricus' => 'Ellenberger, Heinrich',
	'Ellenbergerus, Henricus' => 'Ellenberger, Heinrich',
	'Enoc, Pierre' => 'Enoch, Pierre',
	'Enochus, Petrus' => 'Enoch, Pierre',
	'Ernest Köln, Erzbischof' => 'Ernestus Erzbischof und Kurfürst zu Köln',
	'Ernestus Archiepiscopus Coloniensis' => 'Ernestus Erzbischof und Kurfürst zu Köln',
	'Faber, Georgius' => 'Faber, Georg',
	'Faber, Petrus Johannes' => 'Fabre, Pierre Jean',
	'Fabricius, Johan. Georgius' => 'Fabricius, Johann Georg',
	'Fabricius, Iohannes Georgius' => 'Fabricius, Johann Georg',
	'Fachs, Ludovicus Wolffg.' => 'Fachs, Ludwig Wolfgang',
	'Fausius, Johannes Casparus' => 'Fausius, Johann Caspar',
	'Fehr, Joh. Micahel' => 'Fehr, Johann Michael',
	'Feyrabendt, Sigmuindt' => 'Feyerabend, Sigmund',
	'Fischer, Joh. Andr.' => 'Fischer, Johann Andreas',
	'Forberger, Georgius' => 'Forberger, Georg',
	'Franken-Berg, Abraham vom' => 'Frankenberg, Abraham von',
	'Franckenberg, Abraham vom' => 'Frankenberg, Abraham von',
	'François France, Prince, 1554-1584' => 'Franz Frankreich, Prinz, 1554-1584',
	'Fridericus Dux Wirtembergicus & Teccensis' => 'Friedrich Herzog von Württemberg',
	'Fridercus Ulricus Dux Brunsvicensis & Lunaeburgensis' => 'Friedrich Ulrich, Herzog von Braunschweig-Wolfenbüttel',
	'Fridericus Ulricus Dux Brunsvicensium ac Lunaeburgensium' => 'Friedrich Ulrich, Herzog von Braunschweig-Wolfenbüttel',
	'Friedrich Ulrich Herzog zu Braunschweig und Lüneburg' => 'Friedrich Ulrich, Herzog von Braunschweig-Wolfenbüttel',
	'Furck, S.' => 'Furck, Seb.',
	'Gabler, Johan' => 'Gabler, Johann',
	'Gentersbergerus, Samuel' => 'Genttersberger, Samuel',
	'Georg Wilhelm Herzog zu Braunschweig und Lüneburg' => 'Georg Wilhelm Braunschweig-Lüneburg, Herzog',
	'Gerhard, Joannes' => 'Gerhard, Johann',
	'Goclenius, Rudolphus' => 'Goclenius, Rudolph',
	'Goclenius, Rudolph, der Ältere' => 'Goclenius, Rudolph',
	'Gratarolus, Gulielmus' => 'Grataroli, Guglielmo',
	'Greiff, Sebastianus' => 'Greiff, Sebastian',
	'Guggerus, Joannes Jacobus' => 'Guggerus, Johannes Jacobus',
	'Götze, Thomas Matth.' => 'Götze, Thomas Mattihas',
	'Haffner, M.' => 'Haffner, Melchior',
	'Hagendornius, Ehrenfridus' => 'Hagendorn, Ehrenfried',
	'Hannemann, J. L.' => 'Hannemann, Johann Ludwig',
	'Hartigius, Jo.' => 'Hartigius, Johannes',
	'Hartmann, Joh.' => 'Hartmann, Johann',
	'Hartmannus, Joh.' => 'Hartmann, Johann',
	'Hartmannus, Johan.' => 'Hartmann, Johann',
	'Hartmannus, Johannes' => 'Hartmann, Johann',
	'Hartungus, Valentinus' => 'Hartung, Valentinus',
	'Helmont, Jan Baptista' => 'Helmont, Jan Baptista van',
	'Helmont, Jan Baptiste van' => 'Helmont, Jan Baptista van',
	'Henricus Julius Dux Brunsvicensi ac Lunaeburgensi' => 'Heinrich Julius Braunschweig-Wolfenbüttel, Herzog',
	'Hermann IV., Hessen-Kassel, Landgraf' => 'Hermann IV., Landgraf von Hessen-Kassel',
	'Hermann Köln, Erzbischof, V.' => 'Hermann V., Erzbischof von Köln',
	'Hoffmannus, Joannes' => 'Hoffmann, Johann',
	'Holland, Johann Isaac' => 'Hollandus, Johan Isaac',
	'Horstius, Gregorius' => 'Horst, Gregor',
	'Hubnerus, Bartolomaeus' => 'Hubner, Bartolomäus',
	'Jacobi, Johannes' => 'Jacobi, Johann',
	'Jennis, Lukas' => 'Jennis, Lucas',
	'Jennisius, Lucas' => 'Jennis, Lucas',
	'Joachim Friderich Brandenburg, Kurfürst' => 'Joachim Friedrich Kurfürst zu Brandenburg',
	'Joachim Friderich Markgraf zu Brandenburg' => 'Joachim Friedrich Kurfürst zu Brandenburg',
	'Joachim Friedrich Brandenburg, Kurfürst' => 'Joachim Friedrich Kurfürst zu Brandenburg',
	'Joachim Friedrich Markgraf zu Brandenburg' => 'Joachim Friedrich Kurfürst zu Brandenburg',
	'Joachimus Sigismundus Dux Saxoniae, Angriae & Westphaliae' => 'Joachim Sigismund Herzog zu Sachsen',
	'Joachimus Sigismundus Saxoniae Dux' => 'Joachim Sigismund Herzog zu Sachsen',
	'Joannes Albertus Comes de Oetingen, Dominus in Wallerstain' => 'Johann Albert Graf zu Oettingen Wallenstein',
	'Joannes Electus Episcopus Lybecensis Heres Norwegiae Dux Holsatiae Stormariae & Dithmarsiae' => 'Johann Bischof zu Lübeck',
	'Joannes Georgius Senior Lib. Baro in Froburg' => 'Johann Georg d. Ä. von Froburg',
	'Joannes Philippus Archiepiscopus Moguntinus' => 'Johann Philip Erzbischof von Mainz',
	'Jochim Ernst Erbe zu Norwegen, Herzog zu Schleswig-Holstein-Stormarn' => 'Jochim Ernst Herzog zu Schleswig-Holstein-Stormarn',
	'Jochim Ernst Schleswig Holstein, Herzog' => 'Jochim Ernst Herzog zu Schleswig-Holstein-Stormarn',
	'Joachim Ernst Schleswig Holstein, Herzog' => 'Jochim Ernst Herzog zu Schleswig-Holstein-Stormarn',
	'Johan Philipp Erzbischof zu Mainz' => 'Johann Philipp Mainz, Erzbischof',
	'Johan. Georg Saxonia, Dux' => 'Johann Georg I., Anhalt-Dessau, Fürst',
	'Johann Casimir Herzog zu Sachsen' => 'Johann Casimir Herzog zu Sachsen, Jülich, Cleve und Bergen',
	'Johann Casimirus Hertzog zu Sachsen, Gülich, Cleve und Bergk' => 'Johann Casimir Herzog zu Sachsen, Jülich, Cleve und Bergen',
	'Johann Casimir Sachsen-Coburg, Herzog' => 'Johann Casimir Herzog zu Sachsen, Jülich, Cleve und Bergen',
	'Johann Ernst Sachsen-Weimar, Herzog, I.' => 'Johann Ernst I., Sachsen-Weimar, Herzog.',
	'Johann Friderich Herzog zu Braunschweig und Lüneburg' => 'Johann Friedrich Braunschweig-Lüneburg, Herzog',
	'Johann Georg II., Sachsen, Kurfürst' => 'Johann Georg II., Kurfürst von Sachsen',
	'Johann Georg Sachsen, Kurfürst, I.' => 'Johann Georg I., Kurfürst von Sachsen',
	'Johann Georg der Andere Herzog zu Sachsen, Jülich, Cleve und Berg' => 'Johann Georg I., Kurfürst von Sachsen',
	'Johannes Georgius Dux Saxoniae, Juliae, Cliviae et Montiumum' => 'Johann Georg I., Kurfürst von Sachsen',
	'Johann Pfalz-Zweibrücken, Pfalzgraf, II.' => 'Johann II., Pfalz-Zweibrücken, Pfalzgraf',
	'Johannes Albertus Dux Megapolensius' => 'Johann Albrecht, Herzog zu Mecklenburg',
	'Johannes Fridericus Dux Wirtenbergicus & Teccius' => 'Johann Friedrich, Herzog von Württemberg',
	'Johannes de Rupescissa' => 'Johannes de Rupescissa, OFM',
	'Johannßen Pfalzgraf bei Rhein, In Bayern Herzog' => '', //entfällt
	'Karl I., Braunschweig-Lüneburg, Herzog' => 'Karl I., Herzog von Braunschweig-Lüneburg',
	'Karl Wilhelm Friedrich Brandenburg-Ansbach, Markgraf' => 'Karl Wilhelm Friedrich, Markgraf von Brandenburg-Ansbach',
	'Karpffen, Eberhard von' => 'Karpffen, Eberhardt von',
	'Keerwolff, Lorenz' => 'Keerwolf, Laurens',
	'Kegelerus, Johannes' => 'Kegler, Johannes',
	'Kirstenius, Michael' => 'Kirsten, Michael',
	'Klein, Christianus' => 'Klein, Christian',
	'Kretschmar, Barthol.' => 'Kretschmar, Bartholomäus',
	'Kunckel, Johann' => 'Kunckel, Johannes',
	'Kunigunda Juliana Hassiae Landgravia' => 'Kunigunde Juliane Landgräfin von Hessen',
	'La Fin, Jacobus de' => 'La Fin, Jaques de',
	'La Fin, Jacques de' => 'La Fin, Jaques de',
	'Langelottus, Joel' => 'Langellott, Joel',
	'Langus, Johannes' => 'Lange, Johann',
	'Lauremberg, Petrus' => 'Lauremberg, Peter',
	'Laurembergius, Petrus' => 'Lauremberg, Peter',
	'Leichnerus, E.' => 'Leichnerus, Eccardus',
	'Leopold I., Römisch-Deutsches Reich, Kaiser' => 'Leopold I., Heiliges Römisches Reich, Kaiser',
	'Leopold Römisch-Deutsches Reich, Kaiser, I.' => 'Leopold I., Heiliges Römisches Reich, Kaiser',
	'Leopold Wilhelm Österreich, Erzherzog' => 'Leopold Wilhelm, Erzherzog von Österreich',
	'Leupold, J.' => 'Leupold, Jakob',
	'Linck, Paulus' => 'Linck, Paul',
	'Ludovicus Herzog in Schlesien zur Liegnitz und Brieg' => 'Ludwig Herzog in Schlesien zur Liegnitz und Brieg',
	'Ludovicus Wilhelmus Anhalt, Fürst' => 'Ludwig Wilhelm Fürst zu Anhalt',
	'Ludwig Anhalt-Köthen, Fürst' => 'Ludwig, Fürst zu  Anhalt-Köthen',
	'Ludwig Fürst zu Anhalt' => 'Ludwig, Fürst zu  Anhalt-Köthen',
	'Ludwig I., Anhalt-Köthen, Fürst' => 'Ludwig, Fürst zu  Anhalt-Köthen',
	'London' => '', //entfällt
	'Ludwig Leiningen, Graf' => 'Ludwig Graf zu Leiningen',
	'Maierus, Michael' => 'Maier, Michael',
	'Manßfeldt, Christian Friderich zu' => 'Christian Friedrich Graf zu Mansfeld',
	'Manßfeldt, Hanß Georg Graf zu' => 'Hans Georg Graf zu Mansfeld',
	'Manßfeldt, Joachim Friedrich Graf zu' => 'Joachim Friedrich Graf zu Mansfeld',
	'Manßfeldt, Philipp Graf zu' => 'Philipp Graf zu Mansfeld',
	'Mauricius Dux Saxoniae' => 'Moritz Kurfürst von Sachsen',
	'Mauritius Auracium, Princeps' => 'Maurits van Oranje-Nassau',
	'Mauritius Hassiae Landgravius' => 'Moritz Landgraf zu Hessen-Kassel',
	'Mauritius Landgravius Hassiae' => 'Moritz Landgraf zu Hessen-Kassel',
	'Moritz Hessen-Kassel, Landgraf' => 'Moritz Landgraf zu Hessen-Kassel',
	'Moritz Hessen-Kassel, Landgraf, 1572-1632' => 'Moritz Landgraf zu Hessen-Kassel',
	'Moritz Hessen-Kassel, Landgraf, 1614-1633' => 'Moritz Landgraf zu Hessen-Kassel',
	'Moritz Landgraf von Hessen' => 'Moritz Landgraf zu Hessen-Kassel',
	'Moritz Landgraf zu Hessen' => 'Moritz Landgraf zu Hessen-Kassel',
	'Maximilian Österreich, Erzherzog, 1558-1618' => 'Maximilian Erzherzog von Österreich',
	'Mayer uff Plaussigk, Friederich' => 'Mayer auf Plaussigk, Friederich',
	'Medici, Cosmo de' => 'Medici, Cosimo de',
	'Medici, Franciscus' => 'Medici, Francesco de',
	'Meibomius, Henricus' => 'Meibom, Heinrich',
	'Meibomius, Johan. Heinricus' => 'Meibom, Johann Heinrich',
	'Meibomius, Johannes Heinricus' => 'Meibom, Johann Heinrich',
	'Meisnerus a Commothau, Daniel' => 'Meisnerus, Daniel',
	'Mentzeliuzs, Christianus' => 'Menzelius, Christianus',
	'Merian, M.' => 'Merian, Matthaeus, der Ältere',
	'Merian, Matthaeus' => 'Merian, Matthaeus, der Ältere',
	'Meyer, Heinricus' => 'Meyer, Heinrich',
	'Michael, Joannes' => 'Michael, Johannes',
	'Michaelis, Johannes' => 'Michaelis, Johann',
	'Moltherus, Georgius' => 'Molther, Georg',
	'Moritz Sachsen, Kurfürst' => 'Moritz Kurfürst von Sachsen',
	'Moßbach uff Gönderitz, Ernestus' => 'Moßbach auf Gönderitz, Ernestus',
	'Moßbacher, Ernst' => 'Moßbach, Ernestus',
	'Naumann, Johann' => 'Naumann, Johann, der Jüngere',
	'Neucrantz, Johannes' => 'Neunkrantz, Johann',
	'Nicolaus Flamellus' => 'N. Flamel',
	'Flamellius, Nicolai' => 'N. Flamel',
	'Nollius, Henricus' => 'Nolle, Heinrich',
	'Ohm, Laurent.' => 'Ohm, Laurentius',
	'Olearius, Joannes' => 'Olearius, Johannes',
	'Opitius, Martinus' => 'Opitz, Martin',
	'Orthelius, Andreas' => 'Ortel, Andreas',
	'Paullus van der doort' => 'Paulus van der Doort',
	'Perna, Petrus' => 'Perna, Peter',
	'Petraeus, Heinricus' => 'Petraeus, Henricus',
	'Petri ab Hartenfelß, Georgius Christophorus' => 'Petri von Hartenfels, Georg Christoph',
	'Petri, Georg. Christoph.' => 'Petri von Hartenfels, Georg Christoph',
	'Petri, Georgius Christophorus' => 'Petri von Hartenfels, Georg Christoph',
	'Philipp Pommern-Stettin, Herzog, II.' => 'Philipp II., Herzog zu Pommern-Stettin',
	'Philippus Reinhardus Comes Hanoviensis, Rineccensis et Bipontinus' => 'Philipp Reinhard Graf von Hanau-Münzenberg',
	'Philippus Sigismundus Dux Brunsvicensis & Lunaeburgensis' => 'Philipp Siegismund von Braunschweig-Wolfenbüttel',
	'Philipp Pommern-Stettin, Herzog, II.' => 'Philipp II., Herzog von Pommern-Stettin',
	'Plener, Joh. Adamus' => 'Plener, Johann Adam',
	'Polemann, Joachimus' => 'Polemann, Joachim',
	'Rappoltus, Frider.' => 'Rappoltus, Fridericus',
	'Remmelinus, Johannes' => 'Remmelin, Johann',
	'Renneman, Henningus' => 'Rennemann, Henning',
	'Reusnerus, Hieronymus' => 'Reusner, Hieronymus',
	'Rorscheid, Marcus' => 'Rorscheidt, Marcus',
	'Rudolf August Braunschweig-Lüneburg, Herzog' => 'Rudolf August Herzog von Braunschweig-Lüneburg',
	'Rudolf August Herzog zu Braunschweig und Lüneburg' => 'Rudolf August Herzog von Braunschweig-Lüneburg',
	'Rudolf Römisch-Deutsches Reich, Kaiser, II.' => 'Rudolf II., Heiliges Römisches Reich, Kaiser',
	'Rulandus, Martinus' => 'Ruland, Martin',
	'Rüdinger, Johannes' => 'Rüdinger, Johann',
	'Sachs, Philippus Jacobus' => 'Sachs von Lewenheimb, Philipp Jacob',
	'Sachse de Lewenheimb, Philipp Jakob' => 'Sachs von Lewenheimb, Philipp Jacob',
	'Sayn-Wittgenstein, Anna Magdalena zu' => 'Sayn-Wittgenstein, Anna Magdalena Gräfin zu',
	'Schallerus, Wolfgangus' => 'Schaller, Wolfgang',
	'Scharffius, Davidus Jonathanus' => 'Scharffius, David Jonathan',
	'Schefferus, Wilhelmus Ernestus' => 'Scheffer, Wilhelm Ernst',
	'Schennis, Heinricus a' => 'Schennis, Heinrich von',
	'Schiller, Iulius' => 'Schiller, Julius',
	'Schnizerus, Sigismundus' => 'Schnitzer, Sigismund',
	'Scholzius, Laurentius' => 'Scholz, Lorenz',
	'Schonberger, Ulricus' => 'Schönberger, Ulrich',
	'Schoneberger, Ulricus' => 'Schönberger, Ulrich',
	'Schonerus, Johannes' => 'Schoner, Johannes',
	'Schroeckius, Lucas' => 'Schroeck, Lucas',
	'Schröckius, Lucas' => 'Schroeck, Lucas',
	'Schröcklius, Lucas' => 'Schroeck, Lucas',
	'Schröderus, Ioannes' => 'Schröder, Johann',
	'Schulz, Gottfried' => 'Schultze, Gottfried',
	'Schurtz, Joan-Christophorus a' => 'Schurtz, Johann Christoph von',
	'Schönborn, Philips Ehrwein von' => 'Schönborn, Philip Ehrwein von',
	'Seebach, Johannes Baptista von' => 'Seebach, Johann Baptist von',
	'Sitzmanus, Theodorus' => 'Sitzmannus, Theodorus',
	'Sophia Braunschweig-Lüneburg, Herzogin' => 'Sophia Herzogin von Braunschweig-Lüneburg',
	'Sperlingk, Paulus' => 'Sperling, Paulus',
	'Speyser, Johanguntherus' => 'Speyser, Johann Gunther',
	'Stockman, Joachimus' => 'Stockman, Joachim',
	'Stockmannus Joachimus' => 'Stockman, Joachim',
	'Stockmannus, Joachimus' => 'Stockman, Joachim',
	'Stolberg, Christophorus Guilhelmus Comes in' => 'Christoph Wilhelm Graf zu Stolbert',
	'Stolberg, Christophorus Ludovicus Comes in' => 'Christoph Ludwig Graf zu Stolberg',
	'Sybelist, Wendelinus' => 'Sybelista, Wendelin',
	'Tackius, Joannes' => 'Tacke, Johann',
	'Tampach, Gottfried' => 'Tambach, Gottfried',
	'Tanckius, Joachimus' => 'Tancke, Joachim',
	'Tanckius, Johannes' => 'Tancke, Johannes',
	'Thalhauser, Wolffgang' => 'Thalhauser, Wolfgang',
	'Theodoricus, Georgius' => 'Theodorus, Georgius',
	'Tyrrel, E.' => 'Tyrell, E.',
	'Ursula Herzogin zu Wirttemberg und Teckh' => '	Ursula Herzogin zu Württemberg-Teck',
	'Ursula Herzogin zu Würtemberg und Teck' => 'Ursula Herzogin zu Württemberg-Teck',
	'Volckamerus, Joh. Georgius' => 'Volckamer, Johann Georg',
	'Volckkamerus, Iohannes Georgius' => 'Volckamer, Johann Georg',
	'Waldeck, Christian von' => 'Waldeck, Christian zu',
	'Waldeck, Walrad von' => 'Waldeck, Walrad zu',
	'Wedelius, G. W.' => 'Wedel, Georg Wolfgang',
	'Wedelius, Georg. Wolffgangus' => 'Wedel, Georg Wolfgang',
	'Werdenhagen, Johan. Angelius' => 'Werdenhagen, Johann Angelius von',
	'Westhovius a Westhofen, Willichius' => 'Westhov, Willich',
	'Westonia Angla, Elisabetha Johanna' => 'Weston, Elizabeth Johanna',
	'Westonia, Elisabetha Johanna' => 'Weston, Elizabeth Johanna',
	'Westonia, Elizabetha Johanna' => 'Weston, Elizabeth Johanna',
	'Weyler uff Liechtenberg, Dietrich von und zu' => 'Weyler, Dietrich von und zu',
	'Wichman, Jochim' => 'Wichmann, Joachim',
	'Wilhelm Hessen, Landgraf' => 'Wilhelm Landgraf von Hessen-Kassel',
	'Wilhelmus Hassiae Landgravius' => 'Wilhelm Landgraf von Hessen-Kassel',
	'Wolffard, Marcus' => 'Wolfhard, Marcus',
	'Wolffhard, Marcus' => 'Wolfhard, Marcus',
	'Wust, Balthasar Christoph' => 'Wust, Balthasar Christoph, der Ältere',
	'Wächtler, Caspar' => 'Wächtler, Kaspar',
	'Zvingerus, Theodorus' => 'Zwinger, Theodor',
	'Zwingerus, Jacobus' => 'Zwinger, Jakob'
);

?>
